#!/bin/sh
set -e

# replace our settings in ubroker.properties
sed "s|hostName=localhost|hostName=${NAMESERVER_HOST}|g;s|5162|${NAMESERVER_PORT}|g;s|loggingLevel=1|loggingLevel=${LOGGING_LEVEL}|g" /usr/dlc/properties/ubroker.properties > /usr/dlc/properties/ubroker.properties.new
mv /usr/dlc/properties/ubroker.properties.new /usr/dlc/properties/ubroker.properties

# replace our settings in httpd-vhosts
sed "s|ServerName localhost|ServerName ${VHOST_SERVERNAME}|g;s|localhost-error|${VHOST_SERVERNAME}-error|g;s|localhost-access|${VHOST_SERVERNAME}-access|g;s|ServerAlias www.localhost|ServerAlias ${VHOST_SERVERALIAS}|g;s|    DirectoryIndex|    DirectoryIndex ${VHOST_DIRECTORY_INDEX}|g" /usr/local/apache2/conf/extra/httpd-vhosts.conf > /usr/local/apache2/conf/extra/httpd-vhosts.conf.new
mv /usr/local/apache2/conf/extra/httpd-vhosts.conf.new /usr/local/apache2/conf/extra/httpd-vhosts.conf || true

# do we have a static alias to add?
if [ ! -z "${VHOST_STATIC_ALIAS}" ]
then
  sed "s|    Alias|    Alias \"${VHOST_STATIC_ALIAS}\" \"${VHOST_STATIC_PATH}\"|g" /usr/local/apache2/conf/extra/httpd-vhosts.conf > /usr/local/apache2/conf/extra/httpd-vhosts.conf.new
else
  sed "s|    Alias||g" /usr/local/apache2/conf/extra/httpd-vhosts.conf > /usr/local/apache2/conf/extra/httpd-vhosts.conf.new
fi
mv /usr/local/apache2/conf/extra/httpd-vhosts.conf.new /usr/local/apache2/conf/extra/httpd-vhosts.conf || true

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND